name: servyn
description: Local Service Booking and Trust System

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # State Management
  provider: ^6.1.2

  supabase_flutter: ^2.12.0
  # DI
  get_it: ^9.2.0
  # Navigation
  go_router: ^17.0.1
  # Forms/Inputs
  intl: ^0.20.2  # For dates/Bangla
  geolocator: ^14.0.2  # Location
  google_maps_flutter: ^2.14.0  # Maps
  geocoding: ^3.0.0  # Reverse geocoding
  # Utils
  dartz: ^0.10.1  # For Either/Failure
  http: ^1.2.2  # Network (if not Dio)
  dio: ^5.6.0  # For API (core/network/dio_client.dart)
  # UI
  flutter_svg: ^2.0.10  # Icons
  google_mlkit_text_recognition: ^0.15.0  # or latest
  image_picker: ^1.1.2
  image: ^4.5.4
  permission_handler: ^12.0.1 # Permissions     
  flutter_local_notifications: ^19.5.0
  send_message: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4  # For tests

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/localization/translations/ 

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic

    - family: NotoSansBengali
      fonts:
        - asset: assets/fonts/NotoSansBengali-VariableFont_wdth,wght.ttf
