name: servyn
description: Local Service Booking and Trust System

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # State Management
  provider: ^6.1.2

  supabase_flutter: ^2.12.0
  uuid: ^4.0.0
  # DI
  get_it: ^9.2.0
  # Navigation
  go_router: ^17.0.1
  # Forms/Inputs
  intl: ^0.20.2  # For dates/Bangla
  geolocator: ^14.0.2  # Location
  geocoding: ^3.0.0  # Reverse geocoding
  flutter_map: ^7.0.2  # OpenStreetMap with flutter_map
  latlong2: ^0.9.1  # Latitude/Longitude for flutter_map
  url_launcher: ^6.3.1  # Launch URLs, phone calls
  flutter_polyline_points: ^2.0.0  # For route polylines
  socket_io_client: ^2.0.3+1  # Real-time tracking
  file_picker: ^8.1.4  # File uploads for complaints
  flutter_rating_bar: ^4.0.1  # Rating widget for reviews
  # Utils
  dartz: ^0.10.1  # For Either/Failure
  http: ^1.2.2  # Network (if not Dio)
  dio: ^5.6.0  # For API (core/network/dio_client.dart)
  # UI
  flutter_svg: ^2.0.10  # Icons
  google_mlkit_text_recognition: ^0.15.0  # or latest
  image_picker: ^1.1.2
  image: ^4.5.4
  permission_handler: ^12.0.1 # Permissions     
  flutter_local_notifications: ^19.5.0
  send_message: ^1.0.2
  shared_preferences: ^2.5.4
  clipboard: ^3.0.14
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4  # For tests

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo/
    - assets/fonts/
    - assets/localization/translations/ 
flutter_icons:
  android: true
  ios: true
  image_path: assets/images/logo/logo.png
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/images/logo/logo.png
  adaptive_icon_padding: 20

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo/logo.png
  color_dark: "#0F172A"
  image_dark: assets/images/logo/logo.png
  android_12:
    color: "#FFFFFF"
    image: assets/images/logo/logo.png
    icon_background_color: "#FFFFFF"
  web: true

fonts:
  - family: Inter
    fonts:
      - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
      - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
        style: italic

  - family: NotoSansBengali
    fonts:
      - asset: assets/fonts/NotoSansBengali-VariableFont_wdth,wght.ttf
